### ISSUE TITLE
mirou

### ISSUE THREAD

**Issue by ngdream** [osscameroon/project-ideas#37]
### Introduction

a  funny custom bot for telegram,s oss group

### Description

 # a funny bot for oss community 😄 

### Relevant Technology

- python

### Complexity

- [ ] Beginner - This project requires no or little prior knowledge of the technolog(y|ies) specified to contribute to the project
- [X] Intermediate - The user should have some prior knowledge of the technolog(y|ies) to the point where they know how to use it, but not necessarily all the nooks and crannies of the technology
- [ ] Advanced - The project requires the user to have a good understanding of all components of the project to contribute

### Required time

- [ ] Little work - A couple of days
- [X] Medium work - A week or two
- [ ] Much work - The project will take more than a couple of weeks and serious planning is required

### Categories

- [ ] Mobile app
- [ ] IoT
- [ ] Web app
- [ ] Frontend/UI
- [ ] AI/ML
- [X] APIs/Backend
- [ ] Voice Assistant
- [ ] Developer Tooling
- [ ] Extension/Plugin/Add-On
- [ ] Design/UX
- [ ] AR/VR
- [X] Bots
- [ ] Security
- [ ] Blockchain
- [ ] Futuristic Tech/Something Unique

**Comment by Sanix-Darker** [comment]
Hey there !
please, what do you mean by `a funny bot for oss community` ??? Can you add more description ?

**Comment by ngdream** [comment]
a bot that will allow us to know what issue has been created and what pull request has been made will be a bot that will connect the github platform from oss to telegram

**Comment by Sanix-Darker** [comment]
That bot already exist and it interacting with our osschannel, see : https://t.me/+O7SQfusW8XVmOTFi it has been done here : https://github.com/osscameroon/global-github-actions

**Comment by Sanix-Darker** [comment]
And i see no relation with "funny" here 🤔

**Comment by ngdream** [comment]
> And i see no relation with "funny" here 🤔


are you in the c++ ot group on telegram can i add you ??
