### ISSUE TITLE
Storage

### ISSUE THREAD

**Issue by wdjopa** [osscameroon/project-ideas#40]
### Introduction

Easily store your files online

## What is the purpose ?
Currently, there are several platforms available for storing and sharing files such as GDrive, OneDrive, DropBox, WeTransfer, etc. However, these platforms come with paid plans that are not always in line with individual usage. This results in paying for storage space that may not be needed or will never be used. Cloud platforms such as AWS, Azure and GCloud allow for paying for usage, but they are not user-friendly and require a credit card for payment. This can be an issue in Africa, where many individuals and companies do not have access to credit cards or are not willing to pay the associated currency fees.

## So what is the solution ?
Storage.cm is an innovative solution for managing and storing your files. It is a user-friendly, easy-to-use SaaS platform that allows you to create and manage your files as you need. The platform utilizes a cloud-based infrastructure, such as AWS, to store all the files, and companies have the option to link their existing bucket to import their data. The platform operates on a pay-per-use model, meaning that you only pay for the storage space you actually use. Payment options include mobile money, bank cards, and more. Additionally, users have the ability to use a custom domain and share folders and files publicly, with the option to protect them with a password for added security.

## How to track the project's progress?
Here you have the Notion document (https://djopa.notion.site/Storage-cm-5283e13c1e8d4dd2b27b344b17232ad9) where the project is tracked, so you can know where we are, what we plan to do. You can also see the tasks and offer to work on them if you wish.

### Relevant Technology

I'm thinking about: 

- NextJs (React, Javascript)
- TailwindCSS
- Database (MySQL)
- AWS S3
- ~Serverless (AWS Lambda)
- Payments (Stripe, Mesomb/MyCoolPay, Paypal)

### Complexity

- [ ] Beginner - This project requires no or little prior knowledge of the technolog(y|ies) specified to contribute to the project
- [X] Intermediate - The user should have some prior knowledge of the technolog(y|ies) to the point where they know how to use it, but not necessarily all the nooks and crannies of the technology
- [ ] Advanced - The project requires the user to have a good understanding of all components of the project to contribute

### Required time

- [ ] Little work - A couple of days
- [ ] Medium work - A week or two
- [X] Much work - The project will take more than a couple of weeks and serious planning is required

### Categories

- [ ] Mobile app
- [ ] IoT
- [X] Web app
- [X] Frontend/UI
- [ ] AI/ML
- [X] APIs/Backend
- [ ] Voice Assistant
- [X] Developer Tooling
- [ ] Extension/Plugin/Add-On
- [X] Design/UX
- [ ] AR/VR
- [ ] Bots
- [X] Security
- [ ] Blockchain
- [ ] Futuristic Tech/Something Unique

**Comment by Theryx** [comment]
Hey! I like the Idea
I could help with the design part. I’m in if you don’t mind

**Comment by wdjopa** [comment]
Hello, with pleasure. 
I will create a discord for the project and send you a message when all will be ready.

**Comment by Njimukara** [comment]
Hello @wdjopa, I like the project idea very much, and though I am not an advanced developer, I will like to join your team working on the front end of the project, if you will have me. Thanks

**Comment by elhmn** [comment]
I think we came to the conclusion that opensource solutions already existed and that it was not worth allocating resources on it.
